name: head_tool_counter
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - opencv-python-headless
      - scipy
      - scikit-learn
      - pyyaml
      - shapely
      - ultralytics
      - pytest
